blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/halli75/motion-mirror/discussions
    about: For support, troubleshooting, how-to questions, and general discussion.
